# Generated by Django 3.2.20 on 2023-07-26 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Poll',
        ),
    ]
