# Generated by Django 3.2.20 on 2023-07-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_vote_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='choice',
        ),
    ]
