# Generated by Django 3.2.20 on 2023-07-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_question_poll_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
