# Generated by Django 3.2.20 on 2023-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
